CREATE TABLE IF NOT EXISTS projects(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    priority integer NOT NULL,
    description text,
    deliveryDate date NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    done boolean,
    projectId integer REFERENCES projects(id)
);

INSERT INTO projects(name, priority, description, deliveryDate)
    VALUES ('Make a Web App', 1, 'Using Javascript', '2019-05-12');


INSERT INTO projects(name, priority, description, deliveryDate)
    VALUES ('Make an App', 1, 'Using Dart', '2019-06-12');

INSERT INTO projects(name, priority, description, deliveryDate)
    VALUES ('Make a desktop App', 2, 'Using C++', '2019-07-12');


--INSERT TASK DATA
INSERT INTO tasks(name, done, projectId)
    VALUES ('download VueJs', false, 1);

INSERT INTO tasks(name, done, projectId)
    VALUES ('Create UI', false, 1);

INSERT INTO tasks(name, done, projectId)
    VALUES ('download Flutter', false, 2);

INSERT INTO tasks(name, done, projectId)
    VALUES ('Design UI', false, 2);