CREATE TABLE IF NOT EXISTS projects(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    description text NOT NULL,
    date date NOT NULL,
    github text,
    deploy text,
    photo text
);


INSERT INTO projects(name, description, date, github, deploy, photo)
    VALUES ('Pokémon SPA', 'Single page app developed as my individual project for soyHenry.com using React, Redux, Node.js, Express, and Sequelize/Postgres.', '2021-02-26','https://github.com/martintoz/PI-Pokemon', NULL,'https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/International_Pok%C3%A9mon_logo.svg/1200px-International_Pok%C3%A9mon_logo.svg.png' );


INSERT INTO projects(name, description, date, github, deploy, photo)
    VALUES ('Sneakers ecommerce', 'Store developed as my final group project for soyHenry.com using Apollo/GraphQL, TypeScript, React, Sequelize, and Express', '2021-04-08', 'https://github.com/henry-labs/ecommerce-ft09-g01', 'https://shoes-g1.vercel.app/','https://media.revistagq.com/photos/5ca5f0b83492a97973bf0bfa/master/pass/mejores_cuentas_instagram_zapatillas_sneakers_6578.jpg');

-- CREATE TABLE IF NOT EXISTS tasks(
--     id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
--     name text NOT NULL CHECK (name <> ''),
--     done boolean,
--     projectId integer REFERENCES projects(id)
-- );

-- --INSERT TASK DATA
-- INSERT INTO tasks(name, done, projectId)
--     VALUES ('download VueJs', false, 1);

-- INSERT INTO tasks(name, done, projectId)
--     VALUES ('Create UI', false, 1);

-- INSERT INTO tasks(name, done, projectId)
--     VALUES ('download Flutter', false, 2);

-- INSERT INTO tasks(name, done, projectId)
--     VALUES ('Design UI', false, 2);

sequelize model:create --name Project --attributes name:string,description:string,date:date