CREATE TABLE IF NOT EXISTS projects(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    description text,
    date date NOT NULL
);


INSERT INTO projects(name, description, date)
    VALUES ('Make a Web App', 'Using Javascript', '2019-05-12');


INSERT INTO projects(name, description, date)
    VALUES ('Make an App', 'Using Dart', '2019-06-12');

INSERT INTO projects(name, description, date)
    VALUES ('Make a desktop App', 'Using C++', '2019-07-12');

-- CREATE TABLE IF NOT EXISTS tasks(
--     id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
--     name text NOT NULL CHECK (name <> ''),
--     done boolean,
--     projectId integer REFERENCES projects(id)
-- );

-- --INSERT TASK DATA
-- INSERT INTO tasks(name, done, projectId)
--     VALUES ('download VueJs', false, 1);

-- INSERT INTO tasks(name, done, projectId)
--     VALUES ('Create UI', false, 1);

-- INSERT INTO tasks(name, done, projectId)
--     VALUES ('download Flutter', false, 2);

-- INSERT INTO tasks(name, done, projectId)
--     VALUES ('Design UI', false, 2);